// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IERC20Metadata} from "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {Initializable} from "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import {Ownable2StepUpgradeable} from "@openzeppelin/contracts-upgradeable/access/Ownable2StepUpgradeable.sol";
import {PausableUpgradeable} from "@openzeppelin/contracts-upgradeable/utils/PausableUpgradeable.sol";
import {ReentrancyGuardUpgradeable} from "@openzeppelin/contracts-upgradeable/utils/ReentrancyGuardUpgradeable.sol";
import {UUPSUpgradeable} from "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";
import {MulticallUpgradeable} from "@openzeppelin/contracts-upgradeable/utils/MulticallUpgradeable.sol";

/**
 * @notice Real Groth16 verifier (generated by snarkjs from
 * circuits/state_transition.circom). Verifies the exact public-signal order
 * documented in docs/ARCHITECTURE.md:
 * [positionId, oldCommitment, newCommitment, nullifier, actionId,
 *  newSequence, currentIndexLo, currentIndexHi, publicAmount]
 */
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[9] calldata _pubSignals
    ) external returns (bool);
}

/// @notice Verifier for the liquidation circuit (8 public signals:
/// collateralOut, debtOut, positionId, positionCommitment, prices, threshold,
/// recipient — F5 binding).
interface ILiquidationVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[8] calldata _pubSignals
    ) external view returns (bool);
}

/// @notice Verifier for the risk-transition circuit (borrow/withdraw; 13
/// public signals - the 9 transition fields plus prices, LTV and the
/// recipient (F5 binding)).
interface IRiskVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[13] calldata _pubSignals
    ) external view returns (bool);
}

/// @notice Verifier for the solvency circuit (5 public signals:
/// positionId, positionCommitment, collateralPrice, debtPrice, maxLtvBps).
/// The generated verifier is pure computation, so it is safely callable as
/// `view` (staticcall) — which lets `verifySolvency` be a view as well.
interface ISolvencyVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals
    ) external view returns (bool);
}

/**
 * @notice Minimal oracle boundary. A real oracle adapter plugs in behind this
 * interface; the protocol only requires a price plus the timestamp it was
 * observed at, so freshness can be enforced on-chain.
 */
interface IPriceOracle {
    function getPrice(address asset) external view returns (uint256 price, uint256 updatedAt);
}

/**
 * @notice Minimal per-asset Liquidity Pool boundary. Each supported debt
 * asset may be wired to its own pool via `debtPools`; when wired, borrow
 * payouts are funded by the pool and repayments/liquidation settlements are
 * returned to it. When unwired (`address(0)`), the legacy `debtCustody`
 * reserve path is used unchanged.
 */
interface ILiquidityPool {
    function pullLiquidity(address to, uint256 amount) external;
    function onRepayment(uint256 principal, uint256 interest) external;
    function writeOffBorrows(uint256 amount) external;
    function updateRateBps(uint256 rateBps_) external;
    function totalBorrows() external view returns (uint256);
}

/**
 * @title VeilLend
 * @notice Privacy-first confidential lending for the Horizen ecosystem.
 *
 * Phase 2 — private state + real ZK foundation. The authoritative financial
 * state of a position is a Poseidon commitment over the hidden state
 * (collateral, debt, index snapshot, sequence, control secret, salt). Deposit
 * and repay are real, proof-bound state transitions: a Groth16 proof over
 * circuits/state_transition.circom authorizes them, and the deposited/repaid
 * ERC20 amount is cryptographically bound into the private state.
 *
 * Borrow and withdrawal are live, proof-bound risk transitions. Position
 * closing remains fail-closed ({UnsupportedAction}). The verifier addresses
 * are set once in `initialize` and can only be changed through an
 * owner-authorized UUPS upgrade — proof verification cannot be weakened
 * without that authority.
 *
 * Privacy reality (documented, not hidden): ERC20 transfer amounts are
 * visible at the transaction layer, so per-action deposit/repay amounts are
 * public inputs. What the ZK system protects is the cumulative state —
 * total collateral, debt, interest accrual and health of every position —
 * which never appears on-chain in any readable form.
 */
contract VeilLend is Initializable, Ownable2StepUpgradeable, PausableUpgradeable, ReentrancyGuardUpgradeable, UUPSUpgradeable, MulticallUpgradeable {
    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    using SafeERC20 for IERC20;

    // ------------------------------------------------------------------
    // Constants
    // ------------------------------------------------------------------

    uint256 private constant WAD = 1e18;
    uint256 private constant BPS_DENOMINATOR = 10_000;
    uint256 private constant SECONDS_PER_YEAR = 365 days;

    /// @notice Exclusive upper bound for oracle prices. The ZK circuits
    /// range-check every price with RangeCheck(64); a price at or above this
    /// bound could never appear in a valid proof, so it is rejected at the
    /// oracle boundary instead of bricking an asset's proofs.
    uint256 private constant MAX_ORACLE_PRICE = 1 << 64;

    /// @notice BN254 scalar field order. Public signals larger than this are
    /// non-canonical field aliases and are rejected before verification.
    uint256 public constant SNARK_SCALAR_FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice Transition action ids (must match the circuits).
    uint256 public constant ACTION_DEPOSIT = 1;
    uint256 public constant ACTION_REPAY = 2;
    uint256 public constant ACTION_BORROW = 3;
    uint256 public constant ACTION_WITHDRAW = 4;

    // ------------------------------------------------------------------
    // Types
    // ------------------------------------------------------------------

    enum Status {
        None,
        Active,
        Closed
    }

    /// @notice A private lending position. Collateral/debt amounts are NOT
    /// stored here — the hidden state lives inside `activeCommitment`.
    struct Position {
        address collateralAsset;
        address debtAsset;
        bytes32 activeCommitment;
        uint256 interestIndex; // debt index snapshot (WAD) at last state update
        uint64 sequence; // advances by exactly 1 per verified transition
        Status status;
    }

    struct RateConfig {
        uint64 baseRateBps;
        uint64 slopeBps;
        uint64 targetUtilizationBps;
        uint64 reserveFactorBps;
        uint64 maxLtvBps; // max borrow LTV (numerator over 10000) for solvency proofs
        uint64 liquidationThresholdBps; // liquidation eligibility threshold (numerator over 10000)
    }

    struct DebtIndexState {
        uint256 index; // WAD-scaled; starts at 1e18 and never decreases
        uint64 lastAccrual;
    }

    /// @notice Public inputs of the state-transition circuit, in circuit
    /// declaration order. Every field is public by design (see contract
    /// docs): the private amounts they are derived from never leave the proof.
    struct TransitionInputs {
        uint256 positionId;
        uint256 oldCommitment;
        uint256 newCommitment;
        uint256 nullifier;
        uint256 actionId;
        uint256 newSequence;
        uint256 currentIndexLo; // currentIndex = lo + hi * 2^120
        uint256 currentIndexHi;
        uint256 publicAmount;
    }

    // ------------------------------------------------------------------
    // Errors
    // ------------------------------------------------------------------

    error ZeroAddress();
    error InvalidAmount();
    error InvalidParameter();
    error PositionNotFound();
    error PositionNotActive();
    error AssetNotSupported(address asset);
    error AssetAlreadySupported(address asset);
    error InvalidCommitment();
    error InvalidSequence();
    error InvalidTransitionId();
    error TransitionConsumed();
    error InvalidPublicInput();
    error InvalidAction();
    error StaleIndex();
    error TransferAmountMismatch();
    error ZkVerificationUnavailable();
    error InvalidProof();
    error UnsupportedAction();
    error InsufficientLiquidity();
    error CollateralCustodyNotEmpty(address asset);
    error InsufficientCustody();
    error UnsupportedCollateral();
    error BorrowCapExceeded();
    error InvalidLiquidationAmount();
    error NothingToSettle();
    error OracleNotSet();
    error InvalidPrice();
    error StalePrice();

    // ------------------------------------------------------------------
    // Events
    // ------------------------------------------------------------------

    event PositionCreated(
        uint256 indexed positionId,
        address indexed collateralAsset,
        address indexed debtAsset,
        bytes32 initialCommitment,
        uint64 sequence,
        uint256 interestIndex
    );
    event Deposit(uint256 indexed positionId, address indexed asset, uint256 amount);
    event Repayment(uint256 indexed positionId, address indexed asset, uint256 amount);
    event Borrow(uint256 indexed positionId, address indexed asset, uint256 amount);
    event Withdrawal(uint256 indexed positionId, address indexed asset, uint256 amount);
    event Liquidated(
        uint256 indexed positionId,
        address indexed collateralAsset,
        address indexed debtAsset,
        uint256 collateralOut,
        uint256 debtOut
    );
    event CommitmentUpdated(uint256 indexed positionId, bytes32 newCommitment, uint64 sequence, uint256 interestIndex);
    event InterestAccrued(address indexed asset, uint256 prevIndex, uint256 newIndex, uint64 lastAccrual);
    event CollateralAssetEnabled(address indexed asset);
    event DebtAssetEnabled(address indexed asset, RateConfig config);
    event DebtAssetDisabled(address indexed asset);
    event DebtPoolSet(address indexed asset, address indexed pool);
    event RateConfigUpdated(address indexed asset, RateConfig config);
    event OracleUpdated(address indexed oracle);
    event MaxPriceStalenessUpdated(uint256 maxPriceStaleness);

    // ------------------------------------------------------------------
    // State
    // ------------------------------------------------------------------

    /// @notice Groth16 verifier for the state-transition circuit. Set once in
    /// `initialize`; updatable only through an owner-authorized UUPS upgrade.
    /// `address(0)` keeps the contract fail-closed.
    IGroth16Verifier public verifier;

    /// @notice Groth16 verifier for the solvency (health) circuit.
    ISolvencyVerifier public solvencyVerifier;

    /// @notice Groth16 verifier for risk transitions (borrow/withdraw).
    IRiskVerifier public riskVerifier;

    /// @notice Groth16 verifier for liquidation eligibility.
    ILiquidationVerifier public liquidationVerifier;

    uint256 public nextPositionId;
    mapping(uint256 => Position) public positions;

    mapping(address => bool) public collateralSupported;
    /// @notice Recorded token decimals per asset (set at enable time; used by
    ///         the decimals-aware borrow cap).
    mapping(address => uint8) public assetDecimals;
    mapping(address => bool) public debtSupported;

    /// @notice Aggregate ERC20 custody per asset, bound 1:1 to the hidden
    /// collateral amounts proven by deposit transitions.
    mapping(address => uint256) public collateralCustody;

    /// @notice Aggregate repaid-token custody per debt asset (protocol
    /// reserve until the private supply side exists).
    mapping(address => uint256) public debtCustody;

    /// @notice Per-position SUPPORTED collateral: collateral actually
    /// contributed to this position through verified deposits, reduced by
    /// withdrawals and liquidation seizures. This is a public plaintext
    /// CUSTODY-BOUNDARY control, not the authoritative private state: the
    /// amounts are already public at the ERC20 transfer layer, and the
    /// ledger is provably a LOWER bound of the hidden collateral for every
    /// honestly-originated position (the hidden state may additionally
    /// contain only unbacked, unusable excess). All exits are capped by it,
    /// so fabricated initial commitments cannot extract unbacked value.
    mapping(uint256 => uint256) public supportedCollateral;

    /// @notice Per-position outstanding borrow amount (public plaintext;
    /// borrow amounts are public at the ERC20 layer). Capped against
    /// supportedCollateral so fabricated hidden collateral cannot back real
    /// borrows. Reduced by repayments; written off at liquidation.
    mapping(uint256 => uint256) public borrowOutstanding;

    mapping(address => DebtIndexState) public debtIndexStates;
    mapping(address => RateConfig) public rateConfigs;

    /// @notice Consumed transition nullifiers. An entry is written only
    /// after the corresponding Groth16 proof verifies.
    mapping(bytes32 => bool) public consumedTransitions;

    IPriceOracle public oracle;
    uint256 public maxPriceStaleness; // set to 1 hours in initialize

    /// @notice Per-asset Liquidity Pool wiring (debt-asset architecture prep).
    /// Each supported debt asset maps to its own independent pool contract;
    /// address(0) means "not yet wired" (payouts still come from debtCustody).
    /// Declared LAST so a UUPS upgrade of the deployed proxy stays
    /// storage-layout compatible (append-only state). Pool addresses are
    /// configuration, never hardcoded.
    mapping(address => address) public debtPools;

    // ------------------------------------------------------------------
    // Initialization (UUPS)
    // ------------------------------------------------------------------

    /// @notice UUPS initialization: replaces the former constructor. Same
    /// parameters, same assignments, same owner authority. The owner gains
    /// exactly one new capability: authorizing implementation upgrades
    /// (`_authorizeUpgrade` is `onlyOwner`). No fund-moving authority is
    /// introduced by the upgrade path.
    function initialize(
        address owner_,
        address verifier_,
        address solvencyVerifier_,
        address riskVerifier_,
        address liquidationVerifier_,
        address initialOracle_
    ) external initializer {
        __Ownable_init(owner_);
        __Ownable2Step_init();
        __Pausable_init();
        __ReentrancyGuard_init();
        __UUPSUpgradeable_init();
        __Multicall_init();

        verifier = IGroth16Verifier(verifier_);
        solvencyVerifier = ISolvencyVerifier(solvencyVerifier_);
        riskVerifier = IRiskVerifier(riskVerifier_);
        liquidationVerifier = ILiquidationVerifier(liquidationVerifier_);
        oracle = IPriceOracle(initialOracle_);
        maxPriceStaleness = 1 hours;
    }

    /// @notice UUPS upgrade authorization: owner-only. Upgrading swaps the
    /// implementation code only — it introduces no fund-moving capability by
    /// itself (the implementation holds no owner custody functions; enforced
    /// by the ABI-whitelist test).
    function _authorizeUpgrade(address newImplementation) internal override onlyOwner {}

    // ------------------------------------------------------------------
    // Position creation
    // ------------------------------------------------------------------

    /**
     * @notice Opens a private position. `initialCommitment` is the Poseidon
     * commitment over the caller's initial hidden state (zero collateral and
     * debt, current index snapshot, sequence 0, caller's control secret and
     * salt) computed off-chain. Position control is proven in ZK via the
     * control secret — no plaintext owner identity is recorded.
     */
    function createPosition(
        address collateralAsset,
        address debtAsset,
        bytes32 initialCommitment
    ) external returns (uint256 positionId) {
        if (collateralAsset == address(0) || debtAsset == address(0)) revert ZeroAddress();
        if (!collateralSupported[collateralAsset]) revert AssetNotSupported(collateralAsset);
        if (!debtSupported[debtAsset]) revert AssetNotSupported(debtAsset);
        if (initialCommitment == bytes32(0) || uint256(initialCommitment) >= SNARK_SCALAR_FIELD) revert InvalidCommitment();

        positionId = ++nextPositionId;
        positions[positionId] = Position({
            collateralAsset: collateralAsset,
            debtAsset: debtAsset,
            activeCommitment: initialCommitment,
            interestIndex: debtIndexStates[debtAsset].index,
            sequence: 0,
            status: Status.Active
        });

        emit PositionCreated(
            positionId,
            collateralAsset,
            debtAsset,
            initialCommitment,
            0,
            debtIndexStates[debtAsset].index
        );
    }

    // ------------------------------------------------------------------
    // ZK state transitions (deposit / repay)
    // ------------------------------------------------------------------

    /**
     * @notice Deposits collateral into protocol custody through a verified
     * private state transition. The Groth16 proof proves: the prover knows
     * the old private state (its commitment equals the active commitment),
     * knows the position's control secret, that the sequence advances by
     * exactly one, that the new state hashes to `newCommitment`, and that
     * the hidden collateral grows by exactly `publicAmount` — the same
     * amount pulled from the caller and added to custody here. This binds
     * the ERC20 deposit cryptographically into the private state.
     */
    function deposit(
        TransitionInputs calldata t,
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC
    ) external whenNotPaused nonReentrant {
        _applyVerifiedTransition(t, pA, pB, pC, ACTION_DEPOSIT);
        uint256 received = _pullTokens(_position(t.positionId).collateralAsset, t.publicAmount);
        collateralCustody[_position(t.positionId).collateralAsset] += received;
        supportedCollateral[t.positionId] += received;
        emit Deposit(t.positionId, _position(t.positionId).collateralAsset, received);
    }

    /**
     * @notice Repays debt through a verified private state transition. The
     * circuit computes `newDebt = max(ceil(oldDebt * currentIndex / oldIndex)
     * - publicAmount, 0)` privately; the repaid tokens move into
     * `debtCustody` (protocol reserve until the private supply side exists).
     */
    function repay(
        TransitionInputs calldata t,
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC
    ) external whenNotPaused nonReentrant {
        _applyVerifiedTransition(t, pA, pB, pC, ACTION_REPAY);
        uint256 received = _pullTokens(_position(t.positionId).debtAsset, t.publicAmount);
        uint256 outstanding = borrowOutstanding[t.positionId];
        // principal/interest split from VeilLend's own per-position ledger:
        // the repaid amount covers the position's outstanding principal first;
        // anything beyond it is realized interest for the pool's lenders.
        uint256 principalRepaid = received >= outstanding ? outstanding : received;
        _settleDebt(_position(t.positionId).debtAsset, received, principalRepaid, received - principalRepaid);
        borrowOutstanding[t.positionId] = outstanding - principalRepaid;
        emit Repayment(t.positionId, _position(t.positionId).debtAsset, received);
    }

    /**
     * @dev Shared transition pipeline. Every check happens BEFORE the proof
     * is verified; state effects apply only after verification succeeds.
     */
    function _applyVerifiedTransition(
        TransitionInputs calldata t,
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC,
        uint256 expectedAction
    ) private {
        _requireCanonicalSignals(t);

        IGroth16Verifier v = verifier;
        if (address(v) == address(0)) revert ZkVerificationUnavailable();

        Position storage p = _requireActivePosition(t.positionId);
        // Asset identity binds through positionId (an on-chain position pins
        // its collateral/debt assets); the commitment binds the hidden
        // financial state to that positionId. See docs/ARCHITECTURE.md §2.
        if (t.actionId != expectedAction) revert InvalidAction();
        if (t.publicAmount == 0) revert InvalidAmount();

        // Nullifier replay protection before commitment binding: any replay —
        // of this proof or of the nullifier by a competing transition — fails
        // closed regardless of the commitment state.
        if (t.nullifier == 0) revert InvalidTransitionId();
        if (consumedTransitions[bytes32(t.nullifier)]) revert TransitionConsumed();

        if (t.oldCommitment != uint256(p.activeCommitment)) revert InvalidCommitment();
        if (t.newSequence != uint256(p.sequence) + 1) revert InvalidSequence();
        if (t.newCommitment == 0 || t.newCommitment >= SNARK_SCALAR_FIELD) revert InvalidCommitment();

        // The circuit compounds debt against this exact index.
        if (t.currentIndexLo + t.currentIndexHi * (1 << 120) != debtIndexStates[p.debtAsset].index) revert StaleIndex();

        // Pub-signal order must match the circuit exactly (docs/ARCHITECTURE.md §6).
        uint[9] memory pubSignals = [
            t.positionId,
            t.oldCommitment,
            t.newCommitment,
            t.nullifier,
            t.actionId,
            t.newSequence,
            t.currentIndexLo,
            t.currentIndexHi,
            t.publicAmount
        ];
        if (!v.verifyProof(pA, pB, pC, pubSignals)) revert InvalidProof();

        // --- effects (only reachable with a valid proof) ---
        consumedTransitions[bytes32(t.nullifier)] = true;
        p.activeCommitment = bytes32(t.newCommitment);
        p.sequence = uint64(t.newSequence);
        p.interestIndex = debtIndexStates[p.debtAsset].index;
        emit CommitmentUpdated(t.positionId, bytes32(t.newCommitment), uint64(t.newSequence), p.interestIndex);
    }

    function _pullTokens(address asset, uint256 amount) private returns (uint256 received) {
        uint256 balanceBefore = IERC20(asset).balanceOf(address(this));
        IERC20(asset).safeTransferFrom(msg.sender, address(this), amount);
        received = IERC20(asset).balanceOf(address(this)) - balanceBefore;
        // Fee-on-transfer tokens would break the 1:1 custody binding.
        if (received != amount) revert TransferAmountMismatch();
    }

    /**
     * @dev Settles a LIQUIDATION payment against the liquidated position's
     * pool principal. The recovered principal reduces the pool's
     * totalBorrows; any surplus is realized interest (fee/yield per pool
     * config); an UNRECOVERED residual is realized bad debt — written off
     * from the pool so no ghost principal remains. For unwired assets the
     * legacy debtCustody path is used unchanged.
     */
    function _settleLiquidationPool(address debtAsset, uint256 debtOut, uint256 positionPrincipal) private {
        uint256 principalRecovered = debtOut >= positionPrincipal ? positionPrincipal : debtOut;
        uint256 interestRecovered = debtOut - principalRecovered;
        uint256 badDebt = positionPrincipal - principalRecovered;
        address pool = debtPools[debtAsset];
        if (pool != address(0)) {
            IERC20(debtAsset).safeTransfer(pool, debtOut);
            ILiquidityPool(pool).onRepayment(principalRecovered, interestRecovered);
            if (badDebt > 0) ILiquidityPool(pool).writeOffBorrows(badDebt);
        } else {
            debtCustody[debtAsset] += debtOut;
        }
    }

    /**
     * @notice Owner-only settlement of an ORPHANED position whose private
     * witness is permanently unavailable (testnet recovery). No proof, no
     * witness, no circuit involvement. Collateral is handled FIRST: the
     * entire supportedCollateral is seized and its oracle-parity value in
     * the debt asset is paid by the owner into the position's pool
     * (principal recovery, capped by the pool's totalBorrows). Only the
     * UNRECOVERED residual is realized as bad debt (pool.writeOffBorrows).
     * The seized collateral is transferred to the owner as the recovery
     * payment; the value difference between the collateral and the debt is
     * an economic value difference that stays embedded in the recovered
     * collateral — it is not interest and generates no fee. The position is
     * closed and both ledgers reconcile to zero.
     */
    function settleOrphanPosition(uint256 positionId) external onlyOwner nonReentrant {
        Position storage p = _requireActivePosition(positionId);
        address debtAsset = p.debtAsset;
        uint256 outstanding = borrowOutstanding[positionId];
        uint256 seize = supportedCollateral[positionId];
        if (outstanding == 0 && seize == 0) revert NothingToSettle();
        address pool = debtPools[debtAsset];

        if (pool != address(0) && outstanding > 0) {
            ILiquidityPool lp = ILiquidityPool(pool);
            uint256 poolBorrows = lp.totalBorrows();
            uint256 parityDebt = seize > 0
                ? (seize * _normalizedPrice(p.collateralAsset)) / _normalizedPrice(p.debtAsset)
                : 0;
            uint256 principalRecovered = parityDebt < outstanding ? parityDebt : outstanding;
            uint256 poolClear = principalRecovered > poolBorrows ? poolBorrows : principalRecovered;
            uint256 residual = outstanding - principalRecovered;
            if (residual > 0) lp.writeOffBorrows(residual); // free borrows headroom first
            IERC20(debtAsset).safeTransferFrom(msg.sender, address(this), poolClear);
            IERC20(debtAsset).safeTransfer(pool, poolClear); // forward to the pool (its onRepayment expects the tokens in place)
            lp.onRepayment(poolClear, 0); // principal recovery; orphan settle never realizes interest
        }

        // recovery payment: the seized collateral goes to the caller
        if (seize > 0) {
            supportedCollateral[positionId] = 0;
            collateralCustody[p.collateralAsset] -= seize;
            IERC20(p.collateralAsset).safeTransfer(msg.sender, seize);
        }
        p.status = Status.Closed;
        delete borrowOutstanding[positionId];
        emit OrphanPositionSettled(positionId, seize, outstanding);
    }

    event OrphanPositionSettled(uint256 indexed positionId, uint256 collateralSeized, uint256 debtWrittenOff);

    /**
     * @dev Settles incoming debt tokens (repayment or liquidation payment)
     * into the asset's configured Liquidity Pool, or into the legacy
     * debtCustody reserve when no pool is wired. The tokens are already held
     * by the contract when this runs. VeilLend derives the principal/interest
     * split from its own per-position ledger — never from the pool's
     * aggregate totalBorrows — so one borrower's interest cannot be swallowed
     * by another borrower's outstanding principal.
     */
    function _settleDebt(address debtAsset, uint256 amount, uint256 principal, uint256 interest) private {
        address pool = debtPools[debtAsset];
        if (pool != address(0)) {
            IERC20(debtAsset).safeTransfer(pool, amount);
            ILiquidityPool(pool).onRepayment(principal, interest);
        } else {
            debtCustody[debtAsset] += amount;
        }
    }

    /// @notice Records the token decimals of an asset being enabled. Used by
    /// the decimals-aware borrow cap; the bound of 77 keeps 10^decimals within
    /// uint256 range for the cap arithmetic.
    function _recordAssetDecimals(address asset) private {
        uint8 d = IERC20Metadata(asset).decimals();
        if (d > 77) revert InvalidParameter();
        assetDecimals[asset] = d;
    }

    function _requireCanonicalSignals(TransitionInputs calldata t) private pure {
        if (
            t.positionId >= SNARK_SCALAR_FIELD ||
            t.oldCommitment >= SNARK_SCALAR_FIELD ||
            t.newCommitment >= SNARK_SCALAR_FIELD ||
            t.nullifier >= SNARK_SCALAR_FIELD ||
            t.actionId >= SNARK_SCALAR_FIELD ||
            t.newSequence >= SNARK_SCALAR_FIELD ||
            t.currentIndexLo >= SNARK_SCALAR_FIELD ||
            t.currentIndexHi >= SNARK_SCALAR_FIELD ||
            t.publicAmount >= SNARK_SCALAR_FIELD
        ) revert InvalidPublicInput();
    }

    // ------------------------------------------------------------------
    // ZK solvency (health) verification — Phase 3, Milestone 1
    // ------------------------------------------------------------------

    /**
     * @notice Verifies a Groth16 solvency proof for a position against the
     * CURRENT on-chain commitment and CURRENT fresh oracle prices and risk
     * parameters. The caller supplies only the proof; every public input is
     * derived on-chain, so a proof can never be replayed against a different
     * position, a stale state, or manipulated prices. Reverts unless the
     * circuit's relation holds:
     * `collateral * collateralPrice * 10000 >= debt * debtPrice * maxLtvBps`
     * over hidden amounts bound to the active commitment.
     */
    function verifySolvency(uint256 positionId, uint[2] calldata pA, uint[2][2] calldata pB, uint[2] calldata pC)
        external
        view
    {
        ISolvencyVerifier v = solvencyVerifier;
        if (address(v) == address(0)) revert ZkVerificationUnavailable();

        Position storage p = _requireActivePosition(positionId);
        uint256 collateralPrice = _normalizedPrice(p.collateralAsset);
        uint256 debtPrice = _normalizedPrice(p.debtAsset);
        uint256 maxLtvBps = rateConfigs[p.debtAsset].maxLtvBps;

        uint[5] memory pubSignals = [positionId, uint256(p.activeCommitment), collateralPrice, debtPrice, maxLtvBps];
        if (!v.verifyProof(pA, pB, pC, pubSignals)) revert InvalidProof();
    }

    // ------------------------------------------------------------------
    // Fail-closed protocol actions (require solvency/payout proofs)
    // ------------------------------------------------------------------

    /**
     * @notice Borrows the debt asset against hidden collateral through a
     * verified private state transition. The circuit proves the old state,
     * control secret, sequence+1, nullifier, and — critically — that the
     * POST-borrow position satisfies the solvency inequality against the
     * fresh oracle prices and the configured LTV, all without revealing any
     * balance. Payout comes from the debt-asset custody (protocol reserve
     * funded by repayments). Public inputs are derived on-chain; the caller
     * supplies only the transition fields and the proof.
     */
    function borrow(TransitionInputs calldata t, uint[2] calldata pA, uint[2][2] calldata pB, uint[2] calldata pC)
        external
        whenNotPaused
        nonReentrant
    {
        _applyVerifiedRiskTransition(t, pA, pB, pC, ACTION_BORROW);
        address debtAsset = _position(t.positionId).debtAsset;
        uint256 amount = t.publicAmount;
        // Fabricated hidden collateral cannot back real borrows: the cumulative
        // outstanding debt VALUE is capped by maxLtvBps of the value of the
        // collateral actually contributed to this position. Debt and collateral
        // tokens may use different decimals, so both sides are normalized
        // through the oracle prices and each asset's recorded decimals
        // (cross-multiplied — no division, no rounding):
        //   (outstanding + amount) * debtPrice * 10^collateralDecimals * 10000
        //     <= supportedCollateral * collateralPrice * 10^debtDecimals * maxLtvBps
        // The prices are the same fresh values the proof was just verified
        // against. Overflow is only reachable with absurd token supplies and
        // reverts fail-closed.
        if (exceedsBorrowCap(t.positionId, amount, _position(t.positionId).collateralAsset, debtAsset)) revert BorrowCapExceeded();
        address pool = debtPools[debtAsset];
        if (pool != address(0)) {
            // Pool-funded path: the pool checks its own available liquidity and
            // pays the borrower directly (the F5-bound recipient of the proof).
            ILiquidityPool(pool).pullLiquidity(msg.sender, amount);
        } else {
            // Legacy debtCustody reserve path (unwired assets).
            if (debtCustody[debtAsset] < amount) revert InsufficientLiquidity();
            debtCustody[debtAsset] -= amount;
            IERC20(debtAsset).safeTransfer(msg.sender, amount);
        }
        borrowOutstanding[t.positionId] += amount;
        emit Borrow(t.positionId, debtAsset, amount);
    }

    /**
     * @notice Decimals- and price-aware borrow cap check (view).
     *
     * Returns true when borrowing `amount` more of the position's debt asset
     * would exceed maxLtvBps/10000 of the value of the position's SUPPORTED
     * collateral. Debt and collateral tokens may use different decimals, so
     * both sides are normalized through the oracle prices and each asset's
     * recorded decimals (cross-multiplied — no division, no rounding):
     *   (outstanding + amount) * debtPrice * 10^collateralDecimals * 10000
     *     <= supportedCollateral * collateralPrice * 10^debtDecimals * maxLtvBps
     *
     * Prices are read through the same freshness gate the borrow path uses.
     * Public so the offchain layer can pre-check the exact bound the on-chain
     * borrow path enforces.
     */
    function exceedsBorrowCap(uint256 positionId, uint256 amount, address collateralAsset, address debtAsset)
        public
        view
        returns (bool)
    {
        uint256 collateralPrice = _normalizedPrice(collateralAsset);
        uint256 debtPrice = _normalizedPrice(debtAsset);
        return
            (borrowOutstanding[positionId] + amount) *
            debtPrice *
            BPS_DENOMINATOR >
            supportedCollateral[positionId] *
            collateralPrice *
            rateConfigs[debtAsset].maxLtvBps;
    }

    /**
     * @notice Withdraws collateral through a verified private state
     * transition. The circuit proves the hidden collateral covers the
     * amount AND that the post-withdraw position stays solvent. Funds leave
     * the aggregate custody 1:1 with the hidden balance decrease.
     */
    function withdrawCollateral(TransitionInputs calldata t, uint[2] calldata pA, uint[2][2] calldata pB, uint[2] calldata pC)
        external
        whenNotPaused
        nonReentrant
    {
        _applyVerifiedRiskTransition(t, pA, pB, pC, ACTION_WITHDRAW);
        address collateralAsset = _position(t.positionId).collateralAsset;
        uint256 amount = t.publicAmount;
        // The withdrawal is capped by the collateral actually contributed to
        // this position — fabricated initial claims are unusable.
        if (supportedCollateral[t.positionId] < amount) revert UnsupportedCollateral();
        if (collateralCustody[collateralAsset] < amount) revert InsufficientCustody();
        supportedCollateral[t.positionId] -= amount;
        collateralCustody[collateralAsset] -= amount;
        IERC20(collateralAsset).safeTransfer(msg.sender, amount);
        emit Withdrawal(t.positionId, collateralAsset, amount);
    }

    /**
     * @dev Shared pipeline for risk transitions: same fail-closed ordering
     * as Phase 2 transitions, plus on-chain-derived prices/LTV as extra
     * public inputs (the caller cannot influence them).
     */
    function _applyVerifiedRiskTransition(
        TransitionInputs calldata t,
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC,
        uint256 expectedAction
    ) private {
        _requireCanonicalSignals(t);

        IRiskVerifier v = riskVerifier;
        if (address(v) == address(0)) revert ZkVerificationUnavailable();

        Position storage p = _requireActivePosition(t.positionId);
        if (t.actionId != expectedAction) revert InvalidAction();
        if (t.publicAmount == 0) revert InvalidAmount();

        if (t.nullifier == 0) revert InvalidTransitionId();
        if (consumedTransitions[bytes32(t.nullifier)]) revert TransitionConsumed();

        if (t.oldCommitment != uint256(p.activeCommitment)) revert InvalidCommitment();
        if (t.newSequence != uint256(p.sequence) + 1) revert InvalidSequence();
        if (t.newCommitment == 0 || t.newCommitment >= SNARK_SCALAR_FIELD) revert InvalidCommitment();

        if (t.currentIndexLo + t.currentIndexHi * (1 << 120) != debtIndexStates[p.debtAsset].index) revert StaleIndex();

        uint256 collateralPrice = _normalizedPrice(p.collateralAsset);
        uint256 debtPrice = _normalizedPrice(p.debtAsset);
        uint256 maxLtvBps = rateConfigs[p.debtAsset].maxLtvBps;

        // F5 recipient binding: the payout recipient is derived from
        // msg.sender — the caller cannot supply it, so a proof generated for
        // another address can never verify here and copied mempool proofs
        // are unusable.
        uint[13] memory pubSignals = [
            t.positionId,
            t.oldCommitment,
            t.newCommitment,
            t.nullifier,
            t.actionId,
            t.newSequence,
            t.currentIndexLo,
            t.currentIndexHi,
            t.publicAmount,
            collateralPrice,
            debtPrice,
            maxLtvBps,
            uint256(uint160(msg.sender))
        ];
        if (!v.verifyProof(pA, pB, pC, pubSignals)) revert InvalidProof();

        consumedTransitions[bytes32(t.nullifier)] = true;
        p.activeCommitment = bytes32(t.newCommitment);
        p.sequence = uint64(t.newSequence);
        p.interestIndex = debtIndexStates[p.debtAsset].index;
        emit CommitmentUpdated(t.positionId, bytes32(t.newCommitment), uint64(t.newSequence), p.interestIndex);
    }

    /**
     * @notice Confidential liquidation. The Groth16 proof establishes — over
     * the hidden state bound to the position commitment — that
     * `collateralValue < debtValue * liquidationThreshold` and computes the
     * settlement amounts in-circuit: the entire hidden collateral is seized
     * and the liquidator pays the oracle-parity debt amount (capped at the
     * hidden debt). The liquidator never learns any private state beyond
     * what the public settlement transfers reveal; the contract learns only
     * the proof. The position is closed and any residual hidden debt is
     * written off (socialized bad debt — documented PoC limitation).
     */
    function liquidate(
        uint256 positionId,
        uint256 collateralOut,
        uint256 debtOut,
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC
    ) external whenNotPaused nonReentrant {
        ILiquidationVerifier v = liquidationVerifier;
        if (address(v) == address(0)) revert ZkVerificationUnavailable();
        if (collateralOut == 0 || debtOut == 0) revert InvalidLiquidationAmount();
        if (collateralOut >= SNARK_SCALAR_FIELD || debtOut >= SNARK_SCALAR_FIELD) revert InvalidPublicInput();

        Position storage p = _requireActivePosition(positionId);

        uint256 collateralPrice = _normalizedPrice(p.collateralAsset);
        uint256 debtPrice = _normalizedPrice(p.debtAsset);
        uint256 thresholdBps = rateConfigs[p.debtAsset].liquidationThresholdBps;

        // F5 recipient binding: the settlement recipient is msg.sender,
        // derived on-chain — a proof for another liquidator cannot verify.
        uint[8] memory pubSignals = [
            collateralOut,
            debtOut,
            positionId,
            uint256(p.activeCommitment),
            collateralPrice,
            debtPrice,
            thresholdBps,
            uint256(uint160(msg.sender))
        ];
        if (!v.verifyProof(pA, pB, pC, pubSignals)) revert InvalidProof();

        // The seizure is capped by the collateral actually contributed to
        // this position — fabricated initial claims cannot extract pool
        // collateral. (A position whose hidden collateral exceeds its
        // supported collateral is therefore unliquidatable; that excess is
        // unbacked by construction and only harms its owner.)
        if (supportedCollateral[positionId] < collateralOut) revert UnsupportedCollateral();
        if (collateralCustody[p.collateralAsset] < collateralOut) revert InsufficientCustody();
        supportedCollateral[positionId] -= collateralOut;
        collateralCustody[p.collateralAsset] -= collateralOut;

        // the liquidator pays the settlement debt into the protocol reserve
        uint256 balanceBefore = IERC20(p.debtAsset).balanceOf(address(this));
        IERC20(p.debtAsset).safeTransferFrom(msg.sender, address(this), debtOut);
        if (IERC20(p.debtAsset).balanceOf(address(this)) - balanceBefore != debtOut) revert TransferAmountMismatch();
        // settle the position's pool principal: recovered portion reduces the
        // pool's totalBorrows; the UNRECOVERED residual is realized bad debt
        // (written off) so no ghost principal remains in the pool.
        balanceBefore = borrowOutstanding[positionId]; // reuse local (position pool principal)
        _settleLiquidationPool(p.debtAsset, debtOut, balanceBefore);

        // settlement: collateral goes to the liquidator, position is closed,
        // its outstanding borrow is written off (socialized bad debt)
        p.status = Status.Closed;
        delete borrowOutstanding[positionId];
        IERC20(p.collateralAsset).safeTransfer(msg.sender, collateralOut);
        emit Liquidated(positionId, p.collateralAsset, p.debtAsset, collateralOut, debtOut);
    }

    /**
     * @notice Closing a position (settling remaining collateral/debt
     * privately) is part of the confidential liquidation/settlement phase —
     * not yet implemented. Fail-closed.
     */
    function closePosition(uint256 positionId) external whenNotPaused {
        _requireActivePosition(positionId);
        revert UnsupportedAction();
    }

    // ------------------------------------------------------------------
    // Interest index (public foundation for private debt accounting)
    // ------------------------------------------------------------------

    /**
     * @notice Accrues the public interest index for a debt asset. Private
     * debt compounds against this index inside the ZK circuit:
     * `accruedDebt = ceil(prevPrivateDebt * currentIndex / previousIndex)`,
     * proven exactly (integer ceiling) in the state-transition circuit.
     * Permissionless and allowed while paused.
     */
    function accrueInterest(address debtAsset) external {
        DebtIndexState storage s = debtIndexStates[debtAsset];
        if (s.lastAccrual == 0) revert AssetNotSupported(debtAsset);

        uint256 prevIndex = s.index;
        uint256 dt = block.timestamp - s.lastAccrual;
        if (dt > 0) {
            // Phase 2 rate: base rate only. Utilization-derived terms
            // activate when utilization becomes observable (post-ZK).
            uint256 rateBps = rateConfigs[debtAsset].baseRateBps;
            s.index += (prevIndex * rateBps * dt) / (BPS_DENOMINATOR * SECONDS_PER_YEAR);
            s.lastAccrual = uint64(block.timestamp);
            emit InterestAccrued(debtAsset, prevIndex, s.index, s.lastAccrual);
        }
    }

    /// @notice Current public debt index for an asset (WAD-scaled).
    function currentDebtIndex(address debtAsset) external view returns (uint256) {
        return debtIndexStates[debtAsset].index;
    }

    // ------------------------------------------------------------------
    // Oracle boundary
    // ------------------------------------------------------------------

    /**
     * @notice Returns an asset price only if it is fresh and well-formed.
     * Risky operations (borrow / withdraw / liquidate) gate on it on-chain;
     * stale or absent prices fail closed.
     */
    function getFreshPrice(address asset) public view returns (uint256 price, uint256 updatedAt) {
        IPriceOracle o = oracle;
        if (address(o) == address(0)) revert OracleNotSet();

        (price, updatedAt) = o.getPrice(asset);
        if (price == 0) revert InvalidPrice();
        if (price >= MAX_ORACLE_PRICE) revert InvalidPrice(); // must satisfy the circuits' RangeCheck(64)
        if (updatedAt > block.timestamp) revert InvalidPrice();
        if (block.timestamp - updatedAt > maxPriceStaleness) revert StalePrice();
    }

    /// @notice 18-dec-normalized oracle price: the raw per-token price scaled
    /// so that prices of tokens with different decimals compare exactly inside
    /// the ZK value inequalities. `normalized = raw * 10^(18 - decimals)`.
    /// Requires the asset's recorded decimals to be in [6, 18] (enforced at
    /// enable time) so the normalized price stays inside the circuits'
    /// 104-bit price range.
    function _normalizedPrice(address asset) private view returns (uint256) {
        (uint256 raw, ) = getFreshPrice(asset);
        return raw * (10 ** (18 - assetDecimals[asset]));
    }

    /// @notice Forwards oracle update data to the current IPriceOracle
    /// implementation. Used to push signed Stork updates in the same
    /// transaction as the consuming operation (borrow/withdraw/liquidate),
    /// ensuring the freshest price at execution time. Permissionless —
    /// the Stork contract verifies the publisher signature.
    function pushOracleUpdate(bytes calldata oracleUpdateData) external payable {
        (bool success, bytes memory result) = address(oracle).call{value: msg.value}(oracleUpdateData);
        if (!success) revert OracleUpdateFailed(result);
    }

    error OracleUpdateFailed(bytes returnData);

    // ------------------------------------------------------------------
    // Admin — narrow configuration only
    // ------------------------------------------------------------------

    function enableCollateralAsset(address asset) external onlyOwner {
        if (asset == address(0)) revert ZeroAddress();
        if (collateralSupported[asset]) revert AssetAlreadySupported(asset);
        _recordAssetDecimals(asset);
        collateralSupported[asset] = true;
        emit CollateralAssetEnabled(asset);
    }

    function enableDebtAsset(address asset, RateConfig calldata config) external onlyOwner {
        if (asset == address(0)) revert ZeroAddress();
        if (debtSupported[asset]) revert AssetAlreadySupported(asset);
        _validateRateConfig(config);

        _recordAssetDecimals(asset);
        debtSupported[asset] = true;
        rateConfigs[asset] = config;
        debtIndexStates[asset] = DebtIndexState({index: WAD, lastAccrual: uint64(block.timestamp)});
        emit DebtAssetEnabled(asset, config);
    }

    function setRateConfig(address asset, RateConfig calldata config) external onlyOwner {
        if (!debtSupported[asset]) revert AssetNotSupported(asset);
        _validateRateConfig(config);
        rateConfigs[asset] = config;
        // Keep the wired pool's interest model equal to the real borrower
        // accrual rate (public config — no private state crosses here).
        address pool = debtPools[asset];
        if (pool != address(0)) ILiquidityPool(pool).updateRateBps(config.baseRateBps);
        emit RateConfigUpdated(asset, config);
    }

    /**
     * @notice Removes a debt asset from the active configuration: new
     * positions can no longer be created against it (createPosition checks
     * `debtSupported`). Existing positions keep functioning — repay and the
     * proof pipelines do not gate on this flag — and all configuration,
     * index and custody state is preserved untouched for auditability.
     * Intended for retiring legacy test assets; no balances are moved here.
     */
    function disableDebtAsset(address asset) external onlyOwner {
        if (!debtSupported[asset]) revert AssetNotSupported(asset);
        debtSupported[asset] = false;
        emit DebtAssetDisabled(asset);
    }

    /**
     * @notice ONE-TIME collateral-configuration migration, part of the
     * debtPools upgrade (reinitializer(2), callable only through
     * `upgradeToAndCall`). Takes the list of RETIRED collateral assets as a
     * parameter — no asset is hardcoded — and clears their configuration
     * entries (`collateralSupported` / `assetDecimals`). Fail-safe: an asset
     * still holding custody cannot be cleared. Positions created while the
     * asset was supported remain fully usable; only NEW positions are
     * blocked (createPosition checks the flag).
     */
    function migrateCollateralRetirement(address[] calldata retiredCollateral) external onlyOwner reinitializer(2) {
        for (uint256 i = 0; i < retiredCollateral.length; i++) {
            address asset = retiredCollateral[i];
            if (asset == address(0)) revert ZeroAddress();
            if (collateralCustody[asset] != 0) revert CollateralCustodyNotEmpty(asset);
            collateralSupported[asset] = false;
            assetDecimals[asset] = 0;
        }
    }

    /// @notice Wires a debt asset to its own independent Liquidity Pool.
    /// Pure configuration — the pool contract is not implemented yet and no
    /// funds move. `pool` may be address(0) to unwire. Deployment addresses
    /// are supplied by configuration at wire time, never hardcoded.
    function setDebtPool(address asset, address pool) external onlyOwner {
        if (!debtSupported[asset]) revert AssetNotSupported(asset);
        debtPools[asset] = pool;
        if (pool != address(0)) {
            // Sync the just-wired pool with the current borrower accrual rate.
            ILiquidityPool(pool).updateRateBps(rateConfigs[asset].baseRateBps);
        }
        emit DebtPoolSet(asset, pool);
    }

    function setOracle(address oracle_) external onlyOwner {
        if (oracle_ == address(0)) revert ZeroAddress();
        oracle = IPriceOracle(oracle_);
        emit OracleUpdated(oracle_);
    }

    function setMaxPriceStaleness(uint256 maxPriceStaleness_) external onlyOwner {
        if (maxPriceStaleness_ == 0) revert InvalidParameter();
        maxPriceStaleness = maxPriceStaleness_;
        emit MaxPriceStalenessUpdated(maxPriceStaleness_);
    }

    /**
     * @notice Emergency pause. Blocks all proof-bound state transitions
     * (deposit/repay) and, once they exist, borrow/withdraw/liquidation.
     * Interest accrual, position creation and views remain available; there
     * is no administrative custody path unlocked by pausing.
     */
    function setPaused(bool paused_) external onlyOwner {
        if (paused_) {
            if (!paused()) _pause(); // emits Paused
        } else {
            if (paused()) _unpause(); // emits Unpaused
        }
    }

    function _validateRateConfig(RateConfig calldata config) private pure {
        // maxLtvBps / liquidationThresholdBps must stay within (0, 10000]:
        // 0 would make everything "solvent" / nothing liquidatable, values
        // above 10000 would break the risk model, and anything >= 2^14 could
        // never satisfy the circuits' RangeCheck(14) — permanently bricking
        // an asset's proofs. Rejecting here keeps every configurable value
        // inside the provable range.
        if (
            config.baseRateBps > BPS_DENOMINATOR ||
            config.slopeBps > BPS_DENOMINATOR ||
            config.targetUtilizationBps > BPS_DENOMINATOR ||
            config.reserveFactorBps > BPS_DENOMINATOR ||
            config.maxLtvBps == 0 ||
            config.maxLtvBps > BPS_DENOMINATOR ||
            config.liquidationThresholdBps == 0 ||
            config.liquidationThresholdBps > BPS_DENOMINATOR
        ) revert InvalidParameter();
    }

    function _requireActivePosition(uint256 positionId) private view returns (Position storage p) {
        p = positions[positionId];
        if (p.status == Status.None) revert PositionNotFound();
        if (p.status != Status.Active) revert PositionNotActive();
    }

    function _position(uint256 positionId) private view returns (Position storage p) {
        return positions[positionId];
    }
}
